### ISSUE TITLE
rte_eth_dev_start segfault

### ISSUE THREAD

**Issue by Lesliexpy** [chen622/smart_offload#3]
hi,
I've run your code on X86 server with a bluefield2 in embedded mode. The DPDK-20.11.5 is running on the host.
It happens that it stuck on line 232 in hairpin.c:
main | DEBUG [main.c:79] Running on socket #0
main | DEBUG [main.c:108] ONE port hairpin mode
main | DEBUG [setup.c:56] initializing port: 0
main | DEBUG [setup.c:100] initializing port: 0 done
main | ERROR [hairpin.c:229] 0
main | ERROR [hairpin.c:230] here1
Segmentation fault
I didn't figure out what's wrong with it.

**Comment by chen622** [comment]
I have not tested with BF2, so it may be due to a official compatibility problem. Because the code on line 232 only call the official function `rte_eth_dev_start` with port id. 
Maybe you can try with our [v2 branch](https://github.com/chen622/smart_offload/tree/v2) which we update the DPDK to 21.11. Or you can use DOCA which is design for BlueField DPU.
